package br.com.exp.finance;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main class of FinanceApplication
 * autogenerated by Spring Initializr
 * @author eXP
 * @version 0.1
 * @see <a href="https://docs.spring.io/initializr/docs/current/reference/html/">Spring Initializr</a>
 */

@SpringBootApplication
public class FinanceApplication {

	/**
	 * Main method, starts application
	 * @param args String[] Initialize app
	 */
	public static void main(String[] args) {
		SpringApplication.run(FinanceApplication.class, args);
	}

}
